// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Rechazos.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Clients> Clients { get; set; }

    public virtual DbSet<Lines> Lines { get; set; }

    public virtual DbSet<MachineCodes> MachineCodes { get; set; }

    public virtual DbSet<MesaProcess> MesaProcess { get; set; }

    public virtual DbSet<RamosLines> RamosLines { get; set; }

    public virtual DbSet<Rejections> Rejections { get; set; }

    public virtual DbSet<RjCondition> RjCondition { get; set; }

    public virtual DbSet<RjContainmentaction> RjContainmentaction { get; set; }

    public virtual DbSet<RjDefects> RjDefects { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<ScDefects> ScDefects { get; set; }

    public virtual DbSet<ScMaterial> ScMaterial { get; set; }

    public virtual DbSet<ScTypeScrap> ScTypeScrap { get; set; }

    public virtual DbSet<Scrap> Scrap { get; set; }

    public virtual DbSet<Shifts> Shifts { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Clients>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clients__3214EC07F5814F07");

            entity.Property(e => e.Name)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Lines>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Lines__3214EC07A0D8891D");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<MachineCodes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MachineC__3214EC07442C5112");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.ProcessId).HasColumnName("processId");

            entity.HasOne(d => d.Process).WithMany(p => p.MachineCodes)
                .HasForeignKey(d => d.ProcessId)
                .HasConstraintName("FK__MachineCo__proce__6CD828CA");
        });

        modelBuilder.Entity<MesaProcess>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MesaProc__3214EC07DB9D5C9C");

            entity.Property(e => e.LineId).HasColumnName("lineId");
            entity.Property(e => e.Name)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("name");

            entity.HasOne(d => d.Line).WithMany(p => p.MesaProcess)
                .HasForeignKey(d => d.LineId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__MesaProces__name__69FBBC1F");
        });

        modelBuilder.Entity<RamosLines>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RamosLin__3214EC07BFE10015");

            entity.Property(e => e.Name)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Rejections>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Rejectio__3214EC0786DE5509");

            entity.Property(e => e.Description)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("description");
            entity.Property(e => e.Folio)
                .HasDefaultValueSql("(NEXT VALUE FOR [Seq_Folio])")
                .HasColumnName("folio");
            entity.Property(e => e.Image)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("image");
            entity.Property(e => e.InformedSignature)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("informedSignature");
            entity.Property(e => e.Insepector)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("insepector");
            entity.Property(e => e.NumberOfPieces).HasColumnName("numberOfPieces");
            entity.Property(e => e.OperatorPayroll).HasColumnName("operatorPayroll");
            entity.Property(e => e.PartNumber)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("partNumber");
            entity.Property(e => e.RegistrationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("registrationDate");

            entity.HasOne(d => d.IdClientNavigation).WithMany(p => p.Rejections)
                .HasForeignKey(d => d.IdClient)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Rejection__IdCli__634EBE90");

            entity.HasOne(d => d.IdConditionNavigation).WithMany(p => p.Rejections)
                .HasForeignKey(d => d.IdCondition)
                .HasConstraintName("FK__Rejection__IdCon__6166761E");

            entity.HasOne(d => d.IdContainmentactionNavigation).WithMany(p => p.Rejections)
                .HasForeignKey(d => d.IdContainmentaction)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Rejection__IdCon__6442E2C9");

            entity.HasOne(d => d.IdDefectNavigation).WithMany(p => p.Rejections)
                .HasForeignKey(d => d.IdDefect)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Rejection__IdDef__607251E5");

            entity.HasOne(d => d.IdLineNavigation).WithMany(p => p.Rejections)
                .HasForeignKey(d => d.IdLine)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Rejection__IdLin__625A9A57");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.Rejections)
                .HasForeignKey(d => d.IdUser)
                .HasConstraintName("FK__Rejection__IdUse__19AACF41");
        });

        modelBuilder.Entity<RjCondition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RjCondit__3214EC076CC445F3");

            entity.Property(e => e.Name)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("name");

            entity.HasOne(d => d.IdDefectsNavigation).WithMany(p => p.RjCondition)
                .HasForeignKey(d => d.IdDefects)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__RjConditi__IdDef__74AE54BC");
        });

        modelBuilder.Entity<RjContainmentaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RjContai__3214EC072DC21D99");

            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<RjDefects>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RjDefect__3214EC070A77E270");

            entity.Property(e => e.Name)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC07BB4C88DF");

            entity.HasIndex(e => e.Name, "UQ__Roles__72E12F1B77628FD6").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<ScDefects>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ScDefect__3214EC07698C88EF");

            entity.Property(e => e.Name)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.TypeScrapId).HasColumnName("typeScrapId");

            entity.HasOne(d => d.TypeScrap).WithMany(p => p.ScDefects)
                .HasForeignKey(d => d.TypeScrapId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__ScDefects__typeS__76619304");
        });

        modelBuilder.Entity<ScMaterial>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ScMateri__3214EC07F56443AC");

            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<ScTypeScrap>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ScTypeSc__3214EC07F7594BD2");

            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Scrap>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Scrap__3214EC07DEC3E962");

            entity.Property(e => e.Alloy)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("alloy");
            entity.Property(e => e.DefectId).HasColumnName("defectId");
            entity.Property(e => e.Diameter)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("diameter");
            entity.Property(e => e.LineId).HasColumnName("lineId");
            entity.Property(e => e.MachineId).HasColumnName("machineId");
            entity.Property(e => e.MaterialId).HasColumnName("materialId");
            entity.Property(e => e.PayRollNumber).HasColumnName("payRollNumber");
            entity.Property(e => e.ProcessId).HasColumnName("processId");
            entity.Property(e => e.Rdm)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("RDM");
            entity.Property(e => e.RegistrationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("registrationDate");
            entity.Property(e => e.ShiftId).HasColumnName("shiftId");
            entity.Property(e => e.TypeScrapId).HasColumnName("typeScrapId");
            entity.Property(e => e.Wall)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("wall");
            entity.Property(e => e.Weight)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("weight");

            entity.HasOne(d => d.Defect).WithMany(p => p.Scrap)
                .HasForeignKey(d => d.DefectId)
                .HasConstraintName("FK__Scrap__defectId__0D44F85C");

            entity.HasOne(d => d.Line).WithMany(p => p.Scrap)
                .HasForeignKey(d => d.LineId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Scrap__lineId__09746778");

            entity.HasOne(d => d.Machine).WithMany(p => p.Scrap)
                .HasForeignKey(d => d.MachineId)
                .HasConstraintName("FK__Scrap__machineId__0E391C95");

            entity.HasOne(d => d.Material).WithMany(p => p.Scrap)
                .HasForeignKey(d => d.MaterialId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Scrap__materialI__0B5CAFEA");

            entity.HasOne(d => d.Process).WithMany(p => p.Scrap)
                .HasForeignKey(d => d.ProcessId)
                .HasConstraintName("FK__Scrap__processId__0A688BB1");

            entity.HasOne(d => d.Shift).WithMany(p => p.Scrap)
                .HasForeignKey(d => d.ShiftId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Scrap__RDM__0880433F");

            entity.HasOne(d => d.TypeScrap).WithMany(p => p.Scrap)
                .HasForeignKey(d => d.TypeScrapId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Scrap__typeScrap__0C50D423");
        });

        modelBuilder.Entity<Shifts>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Shifts__3214EC079C6FF2CD");

            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC07AC3EC40B");

            entity.HasIndex(e => e.PayRollNumber, "UQ__Users__9EAAFED528B180D0").IsUnique();

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnName("passwordHash");
            entity.Property(e => e.PayRollNumber).HasColumnName("payRollNumber");
            entity.Property(e => e.RefreshToken)
                .HasMaxLength(256)
                .HasColumnName("refreshToken");
            entity.Property(e => e.RefreshTokenExpiryTime).HasColumnName("refreshTokenExpiryTime");
            entity.Property(e => e.RolId).HasColumnName("rolId");

            entity.HasOne(d => d.Rol).WithMany(p => p.Users)
                .HasForeignKey(d => d.RolId)
                .HasConstraintName("FK__Users__rolId__3493CFA7");
        });
        modelBuilder.HasSequence("Seq_Folio");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}