// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rechazos.Models;

public partial class Lines
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Rejections> Rejections { get; set; } = new List<Rejections>();
}