// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rechazos.Models;

public partial class ScMaterial
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Scrap> Scrap { get; set; } = new List<Scrap>();
}