// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rechazos.Models;

public partial class Scrap
{
    public int Id { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public int? ShiftId { get; set; }

    public int? LineId { get; set; }

    public int? ProcessId { get; set; }

    public int? PayRollNumber { get; set; }

    public int? MaterialId { get; set; }

    public string Alloy { get; set; }

    public string Diameter { get; set; }

    public string Wall { get; set; }

    public int? TypeScrapId { get; set; }

    public int? DefectId { get; set; }

    public string Rdm { get; set; }

    public int? MachineId { get; set; }

    public string Weight { get; set; }

    public virtual ScDefects Defect { get; set; }

    public virtual Lines Line { get; set; }

    public virtual MachineCodes Machine { get; set; }

    public virtual ScMaterial Material { get; set; }

    public virtual MesaProcess Process { get; set; }

    public virtual Shifts Shift { get; set; }

    public virtual ScTypeScrap TypeScrap { get; set; }
}